### ISSUE TITLE
Spelling error in C0_server_dev1.0/readme_for_C0_server.md

### ISSUE THREAD

**Issue by Fristender** [C0hesion-DevTeam/C0hesion#19]
There are four spelling errors in total in the lines 
`HTML escaped password #md5 hased, used for authentifacation teamtype`
and
`HTML escaped password #md5 hased, used for authentifacation ruid`
`hased` should be `hashed`, and `authentifacation` should be `authentification` or `authentication`.

**Comment by rayzliu** [comment]
house

**Comment by Q0k0LaTe** [comment]
dnr c0hesion

**Comment by Q0k0LaTe** [comment]
gnr Q0k0LaTes

**Comment by rayzliu** [comment]
close issue，整好了

**Comment by TheCYPER** [comment]
ok 太帅了

**Comment by TheCYPER** [comment]
谢谢各位
